<div id="content" class="padding10">

							<center><span style="color:#ff3366;"><span style="font-size:31px; line-height:31px;"><b>Welcome to KOS Clan Official Page</b></span> </span></center><br><br><center><span style="color:#99cc33;"><span style="font-size:17px; line-height:17px;"><span style="font-family: 'comic sans ms' "><b>WIN OR LOOSE....WE JUST RUSH FR WIN</b></span> </span> </span></center><br><center><span style="font-size:12px; line-height:12px;"><span style="color:#cc99ff;"><b>"Hail Knights who are the sorrow!"</b></span> </span></center><br><br><span style="font-size:12px; line-height:12px;"><span style="color:#ffcc33;"><span style="font-family: 'comic sans ms' "><b>KOS clan and Servers is founded by Kinnngg on 5th May 2015. This clan is new but becomming most influence clan of SWAT4. KOS clan is Leaded by Hunter.&nbsp;</b></span> </span> </span><br><br><span style="color:#fffce5;"><span style="font-size:12px; line-height:12px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span> </span><br><center><span style="color:#fffce5;"><span style="font-size:12px; line-height:12px;"><b><u>Clan and Server Rules</u></b></span><b><u> </u></b></span></center><br><br><center><ul><li><span style="color:#3366ff;"><span style="font-size:15px; line-height:15px;"><span style="font-family: 'comic sans ms' "><b>Play fair</b></span> </span> </span></li> <li><span style="color:#3366ff;"><span style="font-size:15px; line-height:15px;"><span style="font-family: 'comic sans ms' "><b>No cheats &amp; hack</b></span> </span> </span></li> <li><span style="color:#3366ff;"><span style="font-size:15px; line-height:15px;"><span style="font-family: 'comic sans ms' "><b>Respect other members</b></span> </span> </span></li> <li><span style="color:#3366ff;"><span style="font-size:15px; line-height:15px;"><span style="font-family: 'comic sans ms' "><b>Be active and take part in Clan activities.</b></span> </span> </span></li> <li><span style="color:#3366ff;"><span style="font-size:15px; line-height:15px;"><span style="font-family: 'comic sans ms' "><b>Speak english so that all could understand.</b></span> </span> </span></li> </ul> 
							
							<span style="font-family: 'comic sans ms'; color:#cc99ff;"><b>To Join KoS Clan register at this website and shout in the shoutbox. .&nbsp;</b></span>
							<br><br>
						
						
						<div class="">
						<a href="./?kosclanmembers" class="btn btn-warning btn-block">Members List</a>
						<!--<a href="./?joinkosclan" class="btn btn-default btn-block">Join KoS</a>-->
						<a href="./?kosclandetails" class="btn btn-success btn-block">Clan Details and Rules.</a>
						<br>
						<a href="http://knightofsorrow.clanwebsite.com" target="_blank" class="btn btn-default btn-block">Clan Unofficial Website.</a>
						</div>
</div>